# Generated by Django 4.2.1 on 2023-06-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Bairro',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Cidade',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Estado',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Rua',
            field=models.CharField(max_length=255),
        ),
    ]
