# Generated by Django 4.2.1 on 2023-06-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_alter_usuario_bairro_alter_usuario_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Bairro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Cidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Estado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Rua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
