# Generated by Django 4.2.1 on 2023-06-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0006_alter_usuario_bairro_alter_usuario_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
