# Generated by Django 4.2.1 on 2023-06-08 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0007_alter_usuario_telefone2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='telefone1',
            new_name='tel1',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='telefone2',
            new_name='tel2',
        ),
    ]
