# Generated by Django 4.2.1 on 2023-06-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0008_rename_telefone1_usuario_tel1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomEmp', models.CharField(max_length=255)),
                ('NomFantasia', models.CharField(max_length=255)),
                ('cnpj', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cep', models.IntegerField()),
                ('estado', models.CharField(max_length=255)),
                ('rua', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
            ],
        ),
    ]
