# Generated by Django 4.2.1 on 2023-06-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0009_parceiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiro',
            name='senha',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
