# Generated by Django 4.2.1 on 2023-06-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0010_parceiro_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomMod', models.CharField(max_length=255)),
                ('DescMod', models.CharField(max_length=400)),
                ('QuantAlu', models.IntegerField()),
            ],
        ),
    ]
