# Generated by Django 4.2.1 on 2023-06-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0011_modalidalidade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modalidalidade',
            new_name='Modalidade',
        ),
    ]
