# Generated by Django 4.2.2 on 2023-06-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0012_rename_modalidalidade_modalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=128)),
                ('MasCor', models.IntegerField()),
                ('idade', models.IntegerField()),
                ('Altura', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('observacao', models.TextField()),
            ],
        ),
    ]
